### ISSUE TITLE
Test arbitrarily fail the first time, then works after running a second time. 

### ISSUE THREAD

**Issue by rmanyari** [vitalk/pytest-flask#14]
I have this weird problem that when I run the tests for the first time, some randomly fail and when I run them a second time they all work. Is it possible that since it boots a flask app it needs some kind of warm-up? 

Here is the full error log trace: http://pastebin.com/3PmrTJxS

Thanks.

**Comment by vitalk** [comment]
I've never seen anything like this, and It's hard to guess what's going wrong without any code sample...

Happy New Year! :fireworks: :tada: :santa:

**Comment by rmanyari** [comment]
Sorry I can't paste the app code, I'll try to give it a look myself, I'll let you know if I find anything, thanks!
