### ISSUE TITLE
client_class fixture not working with pytest>=2.7.1

### ISSUE THREAD

**Issue by xuhcc** [vitalk/pytest-flask#32]
After upgrading pytest to version 2.7.1, test that uses `client_class` fixture crashes with the following error:
`ScopeMismatch: You tried to access the 'function' scoped fixture 'client' with a 'module' scoped request object, involved factories`.

pytest-flask version: 0.8.1

**Comment by vitalk** [comment]
Hi @xuhcc!

Can you provide a little more information about this issue to reproduce? The pytest version 2.7.1 works fine for me.

```sh
$ make test
============================== test session starts ===========================
platform darwin -- Python 2.7.8 -- py-1.4.26 -- pytest-2.7.1
rootdir: /Users/vital/Development/web/pytest-flask, inifile:
plugins: flask, xdist
collected 18 items

tests/test_fixtures.py .........
tests/test_live_server.py ......
tests/test_markers.py ...
```

This error may occurs if you reused the `client_class` fixture into module scoped fixture:

```python
import pytest


@pytest.fixture(scope='module')
def foo(client_class):
    return 42


class TestFoo:

    def test_foo(self, foo):
        assert foo == 42
```

**Comment by xuhcc** [comment]
@vitalk 
Indeed, the `client_class` was used in another module-scoped fixture. Changed my code, now everything works.
Thanks for advice!

**Comment by vitalk** [comment]
I'm glad to see it helped :fireworks:
