### ISSUE TITLE
pytest-flask broken when running in docker

### ISSUE THREAD

**Issue by Dinoshauer** [vitalk/pytest-flask#34]
Hey!
Just tried running my test suite in a docker container but it fails with

    AttributeError: 'bool' object has no attribute 'kwargs'

On line 112 in https://github.com/vitalk/pytest-flask/blob/master/pytest_flask/plugin.py#L112
Here's the command to reproduce on the `pytest-flask` repo

    docker run -it --rm -e PYTHONDONTWRITEBYTECODE=1 -v `pwd`:/app python:3.4 sh -xc 'cd /app/ && pip install -r requirements/main.txt && pip install -e . && py.test'

**Comment by vitalk** [comment]
Hello @Dinoshauer! 

Thanks you for reporting this. I found the reason why this bug occurs, so I'll fix it in a few days.

**Comment by Dinoshauer** [comment]
Woohoo! Thanks for the fast feedback. Any chance of a release today? :)

**Comment by vitalk** [comment]
Pypi release will be available soon.

**Comment by vitalk** [comment]
:tada: the new release is available at pypi. Thank you again for reporting!
