### ISSUE TITLE
pytest-flask breaks in pytest 2.8 when using --doctest-modules

### ISSUE THREAD

**Issue by aequitas** [vitalk/pytest-flask#37]
After pytest update to 2.8 this weekend a project which has pytest-flask as dependency installed failed. If i removed the --doctest-modules flag or remove pytest-flask package the test run went fine. Since the pytest-flask module was an artifact of a previous test setup and no longer needed my problem has been resolved by not including the module in de dependencies. So there was no actual use of the module, it was just installed as a test dependency.

The resulting error looks like this but can vary in the filename (eg: test.py) and Session object:

```
AssertionError: assert (<DoctestModule 'test.py'> is None or <DoctestModule 'test.py'> in [<Session 'pytest-flask-bug'>] or isinstance(<DoctestModule 'test.py'>, tuple))
 +  where [<Session 'pytest-flask-bug'>] = [<Session 'pytest-flask-bug'>]
 +    where [<Session 'pytest-flask-bug'>] = <_pytest.runner.SetupState object at 0x103914ac8>.stack
```

This gist shows test case I used and complete log: https://gist.github.com/aequitas/e36d3c8e901aba30ea22

**Comment by vitalk** [comment]
Hi @aequitas! Thank you for detailed report. I'm trying to fix that behavior.

**Comment by vitalk** [comment]
Looks like it's a bug in pytest itself, so I reopen it in pytest repository, see pytest-dev/pytest#1057.

**Comment by aequitas** [comment]
Hi @vitalk, nice find. I only encountered the issue with your module so I reported it here. So sorry to have bothered you with it.
